#!sh
# packs output files of OneShot and wigle_companion to a zip file in Downloads folder, ready to be exported
# place this to {termux folder}/files/usr/bin/

dest=~/storage/downloads/
zipname=$(date +%Y%m%d).zip

cd ~

echo "Exporting networks: "
cat  ./wps/OneShot/reports/stored.csv | wc -l
zip -jr $dest$zipname ./wps/OneShot/reports/ ./wps/wigle_companion/networks.db > /dev/null

echo "Exporting PINs: "
ls -l ./.suroot/.OneShot/pixiewps/ | wc -l
cd .suroot/.OneShot
zip -r $dest$zipname ./pixiewps/ > /dev/null
