#!sh
# packs output files of OneShot and wigle_companion to a zip file in Downloads folder, ready to be exported
# place this to {termux folder}/files/usr/bin/

dest=~/storage/downloads/
zipname=$(date +%Y%m%d).zip

# go to home, so that correct folder tree is created in zip
cd ~

echo "Exporting networks: "
cat  ./wps/OneShot/reports/stored.csv | wc -l
echo "Exporting PINs: "
ls -l ./.suroot/.OneShot/pixiewps/ | wc -l
zip -r $dest$zipname ./wps/OneShot/reports/ ./wps/wigle_companion/networks.db ./.suroot/.OneShot/pixiewps/ > /dev/null

# go back to previous location (from home)
cd -
