#!sudo sh
# sets random MAC and runs WiGLE Companion with active scanning
# place this to {termux folder}/files/usr/bin/

iface="wlan0"
path="/data/data/com.termux/files/home/wps/wigle_companion"


ip link set $iface up
macchanger -r $iface | grep "New"

python3 $path/main.py -i $iface -m real -f networks.db -q $@
