#!sudo sh
# sets random MAC and runs WiGLE Companion
# place this to {termux folder}/files/usr/bin/

iface="wlan0"
path="/data/data/com.termux/files/home/wps/wigle_companion"


ip link set $iface up
macchanger -r $iface | grep "New"

cd $path
python3 main.py -i $iface -m dump -f networks.db -q $@
cd -
