#!sh
# passively runs WiGLE Companion (does not control the interface)
# does not change MAC as it requires to up the interface
# which would interrupt whoever is controlling it now
# and so does not need root
# place this to {termux folder}/files/usr/bin/

iface="wlan0"
path="/data/data/com.termux/files/home/wps/wigle_companion"


cd $path
python3 main.py -i $iface -m dump -f networks.db -q $@
cd -
